import Head from "next/head";
import Image from "next/image";
import bubles from "../public/bubles.jpg";
import mobile from "../public/mobile.png";
import maps from "../public/maps.png";
import {
  FaCloudversify,
  FaGripLines,
  FaArrowCircleRight,
  FaScribd,
  FaUikit,
  FaAirFreshener,
  FaMobileAlt,
  FaFacebookSquare,
  FaInstagram,
  FaTwitterSquare,
  FaLinkedin,
} from "react-icons/fa";
import { TfiWindow } from "react-icons/tfi";
import { GiCircleClaws, GiHamburgerMenu } from "react-icons/gi";
import {
  RiCodeSSlashFill,
  RiMailSendLine,
  RiEditCircleFill,
  RiEditCircleLine,
  RiBuilding2Line,
} from "react-icons/ri";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Circular</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" max-w-screen-2xl m-auto">
        <section className="min-h-screen bg-[url('../public/bubles.jpg')] bg-no-repeat bg-cover">
          <nav className="lg:flex flex text-center justify-between">

            <input type={"checkbox"} id="check" className="hidden"></input>

            <h1 className="text-4xl font-bold flex mt-5 ml-5 justify-between text-white md:ml-20 lg:ml-40">

              <FaCloudversify
                className=" text-white text-5xl mx-3"
                width={"100%"}
                height={"100%"}
              />
              circular
            </h1>

          
              <ul className="float-right mr-10 lg:flex leading-[80px] space-x-4 text-white font-bold uppercase rounded fixed lg:relative h-[100vh] lg:h-0 w-[100%] lg:w-fit top-20 lg:top-0 left-[-100%] lg:left-0 transition-all duration-500 lg:transition-none text-center backdrop-blur-sm">

                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all">
                  <a href="#">HOME</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all">
                  <a href="#">SKILS</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all">
                  <a href="#">SHOWCASE</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all">
                  <a href="#">CAREERS</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all">
                  <a href="#">REACH OUT</a>
                </li>
              </ul>
        

            <label
              for="check"
              className="float-right text-white text-3xl leading-[80px] mt-6 mr-10 lg:hidden"
            >
              <GiHamburgerMenu />
            </label>
            
          </nav>

          <div className="mx-auto text-center my-40">
            <h2 className=" text-6xl font-bold text-white">MEET CIRCULAR</h2>
            <h3 className="text-xl font-light leading-8 pt-5 text-gray-200">
              THIS IS THE AGENCY OF THE FUTURE.
            </h3>
          </div>

          <div className="mx-auto text-center">

            <button className="lg:mx-5 md:mx-5 bg-slate-800 text-white font bold text-2xl rounded-full px-10 py-5 hover:scale-110 hover:transition-all duration-300 ease-in-out ">
              VIDEO PRESENTATION
            </button>

            <button className="lg:mx-5 md:mx-5 bg-transparent text-white font bold text-2xl rounded-full border-2 border-gray-400 px-20 py-5 mt-5 hover:scale-110 hover:transition-all duration-300 ease-in-out">
              LEARN MORE
            </button>

          </div>
        </section>

        <section className=" bg-indigo-900">
          <div className="lg:flex">
            <div className="text-center mx-20 pt-20 lg:w-80 lg:text-left lg:mx-auto">
              <h2 className="text-3xl font-bold text-white">
                WHAT MAKES US A SPECIAL AGENCY
              </h2>

              <div className="hidden lg:flex ">
                <h4 className="text-white pt-5">LET'S DISCUSS YOUR IDEAS</h4>
                <p className="text-white text-2xl pt-5 pl-5">
                  <FaArrowCircleRight />
                </p>
              </div>
            </div>

            <div className="text-xl mx-20 pt-10 pb-10 lg:pt-20 lg:text-2xl lg:mx-auto lg:w-80">
              <h2 className="text-gray-300 leading-8 text-center lg:text-left">
                This should be a short description of the subtitle. It
                shouldnt't be super long or else the content will be unbalanced.
              </h2>
            </div>
          </div>

          <hr class="my-4 mx-auto w-full h-1 bg-gray-500 border-none"></hr>

          <div className="pb-10 lg:flex lg:flex-row lg:justify-around lg:mx-40">
            <div className="mx-10 my-10 shadow-lg py-10">
              <div className="text-white text-5xl pt-5 ">
                <FaScribd className="text-center mx-auto" />
              </div>

              <div className="text-center mx-10">
                <h2 className="text-3xl font-bold text-white py-5">
                  HIGH QUALITY
                </h2>
                <h4 className="text-xl text-gray-300 leading-8">
                  We're not just a theme, the designs look stunning and unique.
                </h4>
              </div>
            </div>

            <div className="mx-10 my-10 shadow-lg pb-10">
              <div className="text-white text-5xl pt-5 ">
                <FaUikit className="text-center mx-auto" />
              </div>

              <div className="text-center mx-10">
                <h2 className="text-3xl font-bold text-white py-5">
                  COOL ANIMATIONS
                </h2>
                <h4 className="text-xl text-gray-300 leading-8">
                  We've included cool animations so we spice things up a bit.
                </h4>
              </div>
            </div>

            <div className="mx-10 my-10 shadow-lg pb-10">
              <div className="text-white text-5xl pt-5 ">
                <FaAirFreshener className="text-center mx-auto" />
              </div>

              <div className="text-center mx-10">
                <h2 className="text-3xl font-bold text-white py-5">
                  EASY TO CHANGE
                </h2>
                <h4 className="text-xl text-gray-300 leading-8">
                  The theme is highly costomizable and can be addapted to
                  evertyhing.
                </h4>
              </div>
            </div>
          </div>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
            <path
              fill="white"
              fill-opacity="1"
              d="M0,32L120,26.7C240,21,480,11,720,42.7C960,75,1200,149,1320,186.7L1440,224L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"
            ></path>
          </svg>
        </section>

        <section>
          <div className="mx-10 my-10">
            <div className="shadow-xl pb-20 p-3 lg:text-left">
              <h2 className="text-4xl font-bold text-indigo-800 lg:text-5xl lg:mx-40">
                WE RAISED THE BAR
              </h2>

              <h4 className="text-xl font-light pt-10 text-indigo-800 leading-8 lg:text-3xl lg:mx-40">
                We're working with passion and we like to belive that we raised
                the level of quality wten it comes to client work. We heve an
                amazing team of designers and developers so you can be sure your
                projects are on the right path with us.
              </h4>
            </div>

            <div className="my-10 lg:mx-40">
              <h3 className="font-bold text-indigo-800 py-5 lg:text-xl">
                OUR MAIN INTERESTS ARE:
              </h3>

              <div className="flex-col gap-16 pt-5 text-3xl text-indigo-500 lg:text-5xl lg:gap-32 lg:flex lg:flex-row">
                <div className="py-5 hover:scale-110 hover:transition-all duration-300 ease-in-out hover:text-indigo-900 cursor-pointer">
                  <FaMobileAlt className="text-center mx-auto" />
                  <p className="text-xl font-bold pt-5 text-center">Mobile</p>
                </div>

                <div className="py-5 hover:scale-110 hover:transition-all duration-300 ease-in-out hover:text-indigo-900 cursor-pointer">
                  <TfiWindow className="text-center mx-auto" />
                  <p className="text-xl font-bold pt-5 text-center">WEB</p>
                </div>

                <div className="py-5 hover:scale-110 hover:transition-all duration-300 ease-in-out hover:text-indigo-900 cursor-pointer">
                  <GiCircleClaws className="text-center mx-auto" />
                  <p className="text-xl font-bold pt-5 text-center">BRANDING</p>
                </div>

                <div className="py-5 hover:scale-110 hover:transition-all duration-300 ease-in-out hover:text-indigo-900 cursor-pointer">
                  <RiCodeSSlashFill className="text-center mx-auto" />
                  <p className="text-xl font-bold pt-5 text-center">
                    DEBELOPMENT
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="my-20">
            <div className="hidden float-right lg:-ml-20 lg:mt-40 lg:rounded-3xl shadow-2xl bg-indigo-800 p-5  h-62 w-52 lg:block">
              <h3 className="text-2xl text-bold text-white">
                Here it should be a short description about the conttrubution of
                the agency.
              </h3>
              <p className="text-white font-bold pt-5">READ MORE</p>
            </div>

            <div
              className=" bg-gradient-to-r from-slate-300 to-slate-700 md:flex
            md:flex-col lg:flex lg:rounded-tr-3xl lg:rounded-br-3xl lg:mr-40 "
            >
              <div className=" lg:h-1/2 lg:w-1/2">
                <Image
                  src={mobile}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <div className="text-center pb-10 md:text-center lg:text-right lg:pr-40 lg:pb-10">
                <h3 className="text-2xl font-bold text-white md:text-3xl lg:text-5xl">
                  PROJECT'S NAME
                </h3>
                <p className="font-medium text-white md:text-xl lg:text-3xl">
                  www.projectswebsite.com
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="my-20">
          <div className="pb-10 md:flex md:flex-col lg:flex lg:flex-row lg:justify-between lg:mx-40">
            <div className=" text-center lg:text-left">
              <h2 className="text-2xl font-bold text-indigo-700 lg:text-5xl">
                WORK WITH US
              </h2>
              <h4 className="text-xl text-gray-500 pt-5 lg:text-2xl lg:max-w-xl">
                We love talented people. Send us your best work and be that name
                on the cool business card.
              </h4>
            </div>

            <div className="shadow-xl rounded-md border-2 border-gray-300  bg-slate-200 h-40 w-70 mx-3 mt-10 py-10 px-10 md:mx-auto md:w-96 lg:h-52 lg:w-80">
              <RiEditCircleFill className="text-2xl text-orange-400" />
              <h3 className="font-bold text-2xl text-indigo-700">YOUR NAME</h3>
              <p className="text-indigo-700 text-xl pt-2">PRODUCT DESIGNER</p>
            </div>
          </div>

          <div
            className="flex mx-5 h-12 w-70 shadow-xl rounded-md border-2 border-gray-300 hover:scale-110 hover:transition-all duration-300 ease-in-out cursor-pointer
          md:mx-auto md:w-80 lg:float-left lg:ml-40 lg:w-80"
          >
            <RiMailSendLine className="text-3xl text-orange-400 ml-7 mt-1" />
            <h3 className="font-bold text-indigo-700 pt-2 pl-2">
              CAREERS@CIRCULAR.COM
            </h3>
          </div>
        </section>

        <section className=" bg-gradient-to-b from-indigo-900 to-indigo-400">
          <div>
            <div className="py-20 mx-auto text-center">
              <h2 className="text-2xl font-bold text-white lg:text-5xl">
                LET'S CONNECT
              </h2>
              <h4 className="text-xl font-light pt-3 text-gray-300 lg:text-2xl">
                Fill in the form bellow and we will be in thac with your
                shortly.
              </h4>
            </div>

            <hr class="mx-auto w-52 h-0.5 bg-gray-400 border-none"></hr>

            <div className="pt-10 text-center mx-auto">
              <h4 className="text-xl font-bold text-white lg:text-2xl">
                I'M THE REPRESENTATIVE OF A:
              </h4>

              <div className="text-5xl flex justify-center gap-6 py-5 text-gray-600 dark:text-gray-400  md:gap-16 lg:gap-16">
                <RiEditCircleLine className="cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out hover:bg-blue-900 rounded-full" />

                <RiBuilding2Line className="cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out hover:bg-blue-900 rounded-md" />
              </div>
            </div>
          </div>

          <div className=" py-20 mx-5 flex flex-col lg:flex lg:flex-row lg:justify-around ">
            <div className="rounded-xl shadow-2xl lg:h-1/2 lg:w-1/2">
              <Image
                src={maps}
                width={"100%"}
                height={"100%"}
              />
            </div>

            <div className="pt-10 mx-3">
              <div className="flex flex-col">
                <h4 className=" font-medium text-white py-2 lg:text-2xl">
                  FULL NAME
                </h4>
                <label class="block">
                  <input
                    type="text"
                    name="text"
                    class="mt-1 px-3 py-2 bg-transparent border shadow-sm border-slate-300 placeholder-slate-200 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-sm focus:ring-1 lg:w-96"
                    placeholder="How should we call you?"
                  />
                </label>

                <h4 className=" font-medium text-white pt-5 lg:text-2xl">
                  EMAIL ADDRESS
                </h4>
                <label class="block">
                  <input
                    type="text"
                    name="text"
                    class="mt-1 px-3 py-2 bg-transparent border shadow-sm border-slate-300 placeholder-slate-200 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-sm focus:ring-1 lg:w-96"
                    placeholder="Enter a valid eamil address"
                  />
                </label>

                <h4 className=" font-medium text-white pt-5 lg:text-2xl">
                  YOUR MESSAGE
                </h4>
                <label class="block">
                  <input
                    type="message"
                    name="message"
                    class="mt-1 px-3 py-2 bg-transparent border shadow-sm border-slate-300 placeholder-slate-200 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-sm focus:ring-1 lg:w-96"
                    placeholder="Tell us more about your project"
                  />
                </label>
              </div>
              <div className="my-10 shadow-2xl bg-blue-900 text-white font-bold rounded-full mx-auto py-3 text-center hover:scale-110 hover:transition-all duration-300 ease-in-out cursor-pointer lg:text-xl">
                <button>SEND MESSAGE</button>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-indigo-900">

          <div className="lg:flex flex text-center">
            <h2 className="text-4xl font-bold flex mt-5 justify-between text-white md:ml-20 lg:mx-auto">
              <FaCloudversify
                className=" text-white text-5xl mx-3"
                width={"100%"}
                height={"100%"}
              />
              circular
            </h2>
            <div className=" my-8 items-center mx-auto hidden md:hidden lg:block">
              <ul className="flex text-center lg:flex lg:justify-between lg:text-xl">
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#">HOME</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#">SKILS</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#">SHOWCASE</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#">CAREERS</a>
                </li>
                <li className="text-gray-200 ml-5 hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#">REACH OUT</a>
                </li>
              </ul>
            </div>

            <div className="flex mt-5 gap-3 mx-auto items-center lg:mt-0">
              <FaFacebookSquare
                className=" text-white text-xl md:text-3xl lg:text-3xl cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out"
                width={"100%"}
                height={"100%"}
              />
              <FaInstagram
                className=" text-white md:text-3xl lg:text-3xl cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out"
                width={"100%"}
                height={"100%"}
              />
              <FaTwitterSquare
                className=" text-white md:text-3xl lg:text-3xl cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out"
                width={"100%"}
                height={"100%"}
              />
              <FaLinkedin
                className=" text-white md:text-3xl lg:text-3xl cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
